run: fp sb shell file_process.cpp squashbug.cpp Assignment2_29_20CS10074_20CS30028_20CS10040_20CS10061.cpp
fp:
	g++ file_process.cpp -o fp
sb:
	g++ squashbug.cpp -o sb
shell:
	g++ Assignment2_29_20CS10074_20CS30028_20CS10040_20CS10061.cpp -o shell -lreadline

clean:
	rm -f sb fp shell